### ISSUE TITLE
Week 4 Review Ticket

### ISSUE THREAD

**Issue by guapbeast** [guapbeast/flask_portfolio#7]
Ethan G. 6/5

Study Plan: 

1. To go through each of the 5 college-board Units and review all of the videos and take new notes to study. 
2.  Watch videos about preparing for the AP Computer Science Principles Exam
3.  Practice Questions

Review Ticket Week 4

Individual
- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on Replit/Intellij

Hacks.
- [x] Hack #1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack #2 Add logout to CRUD screen
- [x] Hack #3 Add login_required to another portion of the project
- [x] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.
